# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-06 22:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=128, verbose_name="Answer's text")),
                ('correct', models.BooleanField(default=False, verbose_name='Correct')),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('experience', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('AC', 'Active'), ('CN', 'Cancelled'), ('FN', 'Finished')], default='AC', max_length=2)),
                ('result', models.CharField(choices=[('P', 'Pass'), ('F', 'Fail'), ('TBD', 'Pending')], default='TBD', max_length=3)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Evaluator.Candidate')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('id_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300, verbose_name='Description')),
                ('difficulty', models.CharField(choices=[('H', 'Hard'), ('M', 'Medium'), ('E', 'Easy')], default='M', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('position', models.ManyToManyField(to='Evaluator.Position')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='skill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Evaluator.Skill'),
        ),
        migrations.AddField(
            model_name='interview',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Evaluator.Position'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='position_applied',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Evaluator.Position'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Evaluator.Question'),
        ),
    ]
