# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-25 19:03
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evaluator', '0004_candidate_contact_primary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ManyToManyField(to='Evaluator.Question')),
            ],
        ),
        migrations.AlterField(
            model_name='candidate',
            name='contact_primary',
            field=models.CharField(max_length=20, null=True, validators=[django.core.validators.RegexValidator(regex='\\d+')]),
        ),
    ]
