# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-04 21:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Evaluator', '0009_question_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='exam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Evaluator.Exam'),
        ),
    ]
