# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-12 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evaluator', '0011_auto_20180423_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='qset',
        ),
        migrations.AddField(
            model_name='question',
            name='qset',
            field=models.ManyToManyField(to='Evaluator.QuestionSet'),
        ),
    ]
