# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-18 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evaluator', '0012_auto_20180912_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='exp_needed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='position',
            name='j_type',
            field=models.CharField(choices=[('P', 'Permanent'), ('T', 'Temporary'), ('I', 'Intern')], default='P', max_length=1),
        ),
        migrations.AddField(
            model_name='position',
            name='location',
            field=models.CharField(default='Pune', max_length=100),
        ),
        migrations.AddField(
            model_name='position',
            name='technology',
            field=models.TextField(default=''),
        ),
    ]
