# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-18 11:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Evaluator', '0013_auto_20180918_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalInterview',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('AC', 'Active'), ('CN', 'Cancelled'), ('FN', 'Finished')], default='AC', max_length=2)),
                ('result', models.CharField(choices=[('P', 'Pass'), ('F', 'Fail'), ('TBD', 'Pending')], default='TBD', max_length=3)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('candidate', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Evaluator.Candidate')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('position', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Evaluator.Position')),
                ('question_set', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Evaluator.QuestionSet')),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical interview',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
