# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-20 11:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Evaluator', '0014_historicalinterview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('round_type', models.CharField(choices=[('U', 'Undecided'), ('F2F', 'Face to Face'), ('SKYPE', 'Skype Call'), ('TP', 'Telephonic'), ('VC', 'Client Video Call'), ('FD', 'Final Discussion')], default='U', max_length=10)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='interview',
            name='question_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Evaluator.QuestionSet'),
        ),
        migrations.AddField(
            model_name='round',
            name='interview',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Evaluator.Interview'),
        ),
    ]
