# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-20 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evaluator', '0015_auto_20180920_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='round_type',
            field=models.CharField(choices=[('ADV', 'Advanced'), ('RJ', 'Rejected'), ('CN', 'Cancelled'), ('DNA', 'Did Not Appear'), ('DNO', 'Did Not Accept Offer'), ('RS', 'Rescheduled'), ('W', 'Waiting'), ('S', 'Selected')], default='W', max_length=5),
        ),
    ]
