# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-20 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evaluator', '0017_auto_20180920_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinterview',
            name='result',
            field=models.CharField(choices=[('S', 'Selected'), ('R', 'Rejected'), ('J', 'Joined'), ('DNJ', 'Did Not Join'), ('TBD', 'Pending')], default='TBD', max_length=3),
        ),
        migrations.AlterField(
            model_name='interview',
            name='result',
            field=models.CharField(choices=[('S', 'Selected'), ('R', 'Rejected'), ('J', 'Joined'), ('DNJ', 'Did Not Join'), ('TBD', 'Pending')], default='TBD', max_length=3),
        ),
    ]
