# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-20 13:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evaluator', '0018_auto_20180920_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
        migrations.AddField(
            model_name='round',
            name='modified_on',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
    ]
