# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-21 12:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Evaluator', '0020_auto_20180921_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='contact_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
