# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-25 08:42
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Evaluator', '0021_round_contact_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20, null=True, validators=[django.core.validators.RegexValidator(regex='\\d+')])),
                ('address', models.TextField()),
                ('v_type', models.CharField(choices=[('O', 'Online'), ('R', 'Reference'), ('RS', 'Recruitment Service'), ('OT', 'Other'), ('N', 'None')], default='N', max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='candidate',
            name='vendor_applied',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Evaluator.Vendor'),
        ),
    ]
