# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-25 09:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Evaluator', '0022_auto_20180925_1412'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='vendor_applied',
            new_name='vendor',
        ),
    ]
