# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-25 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evaluator', '0024_candidate_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='comments',
            field=models.CharField(default='', max_length=300, null=True),
        ),
    ]
