# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-29 19:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Evaluator', '0031_aspect_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewRatingSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Evaluator.RatingSheet')),
            ],
        ),
        migrations.RemoveField(
            model_name='rating',
            name='interview',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='rating_sheet',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
        migrations.AddField(
            model_name='historicalinterview',
            name='rating_sheet',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Evaluator.InterviewRatingSheet'),
        ),
        migrations.AddField(
            model_name='interview',
            name='rating_sheet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Evaluator.InterviewRatingSheet'),
        ),
    ]
