# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-29 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evaluator', '0032_auto_20180930_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewratingsheet',
            name='name',
            field=models.CharField(default='MySheet', max_length=200),
        ),
    ]
