# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-05 09:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Evaluator', '0034_auto_20180930_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingAspect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(default='', null=True)),
                ('interview_rating_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Evaluator.InterviewRatingSheet')),
            ],
        ),
    ]
