# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-05 09:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Evaluator', '0035_ratingaspect'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aspect',
            name='points',
        ),
    ]
