# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-06 21:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Evaluator', '0037_ratingaspect_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewratingsheet',
            name='rate_sheet',
        ),
    ]
