# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-07 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evaluator', '0039_auto_20181007_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingaspect',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
