# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-07 18:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Evaluator', '0040_auto_20181007_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewratingsheet',
            name='round_name',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Evaluator.Round'),
        ),
    ]
