# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-08 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evaluator', '0041_auto_20181007_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='comments',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
    ]
