# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-10 18:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Evaluator', '0042_auto_20181008_1730'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ratingaspect',
            old_name='description',
            new_name='comment',
        ),
    ]
