# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-12 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evaluator', '0043_auto_20181011_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='skill',
            field=models.ManyToManyField(to='Evaluator.Skill'),
        ),
    ]
