# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-12 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evaluator', '0044_candidate_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='aspect',
            name='expected_rate',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
