# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-12 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evaluator', '0045_aspect_expected_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingaspect',
            name='expected_points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
