# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-27 13:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Evaluator', '0047_interviewratingsheet_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='round',
            name='modified_on',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
