# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-11 11:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evaluator', '0050_round_supporting_interviewer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='supporting_interviewer',
            field=models.ManyToManyField(blank=True, related_name='supporters', to=settings.AUTH_USER_MODEL),
        ),
    ]
