# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-28 08:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Evaluator', '0051_auto_20190311_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOpenings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_openings', models.PositiveIntegerField(default=1)),
                ('posted_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Evaluator.Position')),
            ],
        ),
    ]
