# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-28 08:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Evaluator', '0052_jobopenings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobOpenings',
            new_name='JobOpening',
        ),
    ]
