# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-15 11:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Evaluator', '0054_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='candidate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Evaluator.Candidate'),
        ),
    ]
